/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author u04619081159
 */
public class JFrm_ITO_Principal extends javax.swing.JFrame {

    /**
     * Creates new form JFrm_ITO_Principal
     */
    public JFrm_ITO_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuITO_Cadastro = new javax.swing.JMenu();
        jMniITO_Usuarios = new javax.swing.JMenuItem();
        jMniITO_Produtos = new javax.swing.JMenuItem();
        jMniITO_Clientes = new javax.swing.JMenuItem();
        jMniITO_Vendedor = new javax.swing.JMenuItem();
        jMniITO_Sair = new javax.swing.JMenuItem();
        jMnuITO_Movimentos = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMnuITO_Cadastro.setText("Cadastros");

        jMniITO_Usuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_NUMPAD4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMniITO_Usuarios.setText("Usuarios");
        jMniITO_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniITO_UsuariosActionPerformed(evt);
            }
        });
        jMnuITO_Cadastro.add(jMniITO_Usuarios);

        jMniITO_Produtos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_NUMPAD0, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMniITO_Produtos.setText("Produtos");
        jMniITO_Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniITO_ProdutosActionPerformed(evt);
            }
        });
        jMnuITO_Cadastro.add(jMniITO_Produtos);

        jMniITO_Clientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_NUMPAD9, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMniITO_Clientes.setText("Clientes");
        jMnuITO_Cadastro.add(jMniITO_Clientes);

        jMniITO_Vendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_NUMPAD8, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMniITO_Vendedor.setText("Vendedor");
        jMniITO_Vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniITO_VendedorActionPerformed(evt);
            }
        });
        jMnuITO_Cadastro.add(jMniITO_Vendedor);

        jMniITO_Sair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMniITO_Sair.setText("Sair");
        jMnuITO_Cadastro.add(jMniITO_Sair);

        jMenuBar1.add(jMnuITO_Cadastro);

        jMnuITO_Movimentos.setText("Movimentos");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_NUMPAD7, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem6.setText("Vendas");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMnuITO_Movimentos.add(jMenuItem6);

        jMenuBar1.add(jMnuITO_Movimentos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMniITO_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniITO_UsuariosActionPerformed
        // TODO add your handling code here:
        JDlg_ITO_Usuarios jDlgUsuarios = new JDlg_ITO_Usuarios(this, true);
        jDlgUsuarios.setVisible(true);
    }//GEN-LAST:event_jMniITO_UsuariosActionPerformed

    private void jMniITO_VendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniITO_VendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMniITO_VendedorActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMniITO_ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniITO_ProdutosActionPerformed
        JDlg_ITO_Produtos jDlgProdutos = new JDlg_ITO_Produtos(this, true);
        jDlgProdutos.setVisible(true);       
    }//GEN-LAST:event_jMniITO_ProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrm_ITO_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrm_ITO_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrm_ITO_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrm_ITO_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrm_ITO_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMniITO_Clientes;
    private javax.swing.JMenuItem jMniITO_Produtos;
    private javax.swing.JMenuItem jMniITO_Sair;
    private javax.swing.JMenuItem jMniITO_Usuarios;
    private javax.swing.JMenuItem jMniITO_Vendedor;
    private javax.swing.JMenu jMnuITO_Cadastro;
    private javax.swing.JMenu jMnuITO_Movimentos;
    // End of variables declaration//GEN-END:variables
}
